In [23]:
import numpy as np
from itertools import product

In [77]:
class GameOfLife:
    
    def __init__(self, filepath):
        
        self.grid = np.loadtxt(filepath, dtype=int, converters=float)     
            
    def getNeighbors(self, row, col):
        
        M, L = self.grid.shape

        row_offsets = [-1, 0, 1]
        col_offsets = [-1, 0, 1]
        neighbors = {((row+r)%M, (col+c)%L) for r, c in product(row_offsets, col_offsets)}
        neighbors.discard((row, col))

        return list(neighbors)
    
    def game(self, timesteps):
        
        for _ in timesteps:
            
            grid = np.copy(self.grid)
            alive = np.where(grid == 1)
            dead = np.where(grid == 0)
            alive_neighbors = np.array([len(self.getNeighbors(n[0], n[1])) for n in zip(*alive)])
            dead_neighbors = np.array([len(self.getNeighbors(n[0], n[1])) for n in zip(*dead)])
            to_kill = np.where((alive_neighbors < 2) | (alive_neighbors > 3))
            to_revive = np.where(dead_neighbors == 3)

In [53]:
gol = GameOfLife('test.txt')

In [54]:
gol.grid

array([[ 6, 17, 16, 10,  4, 19, 19, 19,  6, 17],
       [13,  1,  4,  8,  2,  2, 14, 11,  8, 19],
       [ 4, 18,  9,  5,  6,  1,  3,  7, 11,  5],
       [11,  5, 19, 13,  1, 10, 12, 17,  6,  5],
       [18, 10, 18,  5,  8, 18, 17, 12, 13, 17],
       [ 6, 12,  6,  2, 13,  5,  1, 11, 11, 10],
       [14, 10, 18,  7,  2, 19,  7, 14,  6, 12],
       [ 5, 15,  6,  0,  9, 10,  1, 11, 11,  2],
       [17, 12, 14,  1, 10, 17, 13, 14, 18,  0],
       [18,  1, 18, 18,  1,  3,  5,  7,  1, 12]])

In [55]:
dupa = gol.getNeighbors(9, 2)
dupa

[(0, 1), (9, 3), (8, 1), (0, 3), (8, 3), (0, 2), (8, 2), (9, 1)]

In [56]:
a, b = zip(*dupa)

In [57]:
a

(0, 9, 8, 0, 8, 0, 8, 9)

In [58]:
b

(1, 3, 1, 3, 3, 2, 2, 1)

In [59]:
gol.grid[a, b]

array([17, 18, 12, 10,  1, 16, 14,  1])

In [17]:
dupa = np.random.randint(low=0, high=20, size=(10, 10), dtype=int)

In [18]:
np.savetxt('test.txt', dupa)

In [60]:
test = np.loadtxt('test.txt', dtype=int, converters=float)
test

array([[ 6, 17, 16, 10,  4, 19, 19, 19,  6, 17],
       [13,  1,  4,  8,  2,  2, 14, 11,  8, 19],
       [ 4, 18,  9,  5,  6,  1,  3,  7, 11,  5],
       [11,  5, 19, 13,  1, 10, 12, 17,  6,  5],
       [18, 10, 18,  5,  8, 18, 17, 12, 13, 17],
       [ 6, 12,  6,  2, 13,  5,  1, 11, 11, 10],
       [14, 10, 18,  7,  2, 19,  7, 14,  6, 12],
       [ 5, 15,  6,  0,  9, 10,  1, 11, 11,  2],
       [17, 12, 14,  1, 10, 17, 13, 14, 18,  0],
       [18,  1, 18, 18,  1,  3,  5,  7,  1, 12]])

In [73]:
a = np.where(test == 1)
a

(array([1, 2, 3, 5, 7, 8, 9, 9, 9], dtype=int64),
 array([1, 5, 4, 6, 6, 3, 1, 4, 8], dtype=int64))

In [76]:
[[i[0], i[1]] for i in zip(*a)]

[[1, 1], [2, 5], [3, 4], [5, 6], [7, 6], [8, 3], [9, 1], [9, 4], [9, 8]]

In [84]:
dupa = np.random.randint(0, 100, 30)
dupa

array([60, 42, 30, 86, 62, 42, 71,  3, 98, 11, 36, 62, 95,  6, 44, 14, 98,
       10,  2, 70, 27,  4, 44, 66, 95, 83, 35, 26,  3, 90])

In [87]:
np.where((dupa > 80) | (dupa < 5))

(array([ 3,  7,  8, 12, 16, 18, 21, 24, 25, 28, 29], dtype=int64),)

In [ ]:
inds = 

In [88]:
a[0]

(array([1, 2, 3, 5, 7, 8, 9, 9, 9], dtype=int64),
 array([1, 5, 4, 6, 6, 3, 1, 4, 8], dtype=int64))